# Generated by Django 5.2.8 on 2025-12-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_entry_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="body_text_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="entry",
            name="tags",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
