"""
Django settings for lesson_drf project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv
from celery.schedules import crontab
from kombu import Queue

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    #  Django REST Framework
    'rest_framework',
    'rest_framework_simplejwt',
    'djoser',
    'drf_spectacular',
    'debug_toolbar',
    # inne aplikacje
    'api',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Ustawiamy drf-spectacular jako domyślny generator schematu
    'DEFAULT_SCHEMA_CLASS':'drf_spectacular.openapi.AutoSchema',
}

# Opcjonalna, dodatkowa konfiguracja Simple JWT

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# Opcjonalna, ale zalecana konfiguracja dla drf-spectacular
SPECTACULAR_SETTINGS = {
    'TITLE': 'Moje Wspaniałe API Projektu',
    'DESCRIPTION': 'Dokumentacja dla API, które robi niesamowite rzeczy.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False, # Zazwyczaj nie chcemy udostępniać pliku schematu publicznie
}

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware', 
                    # ^^^ Dodaj jak najwyżej, ale po GZipMiddleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', # Zarządza sesjami, ustawia ciasteczka
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', # Ochrona przed atakami CSRF (recznie serwowane formularze)
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Dodaje obiekt użytkownika do zapytania (sprawdzi, czy User jest zalogowany)
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'lesson_drf.middleware.HTTPMethodMiddleware',
]

ROOT_URLCONF = "lesson_drf.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lesson_drf.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('ENGINE', 'django.db.backends.postgresql'), # Informuje Django, że używamy PostgreSQL
        'NAME': os.getenv('NAME', 'django_rest_db'),              # Nazwa Twojej bazy danych
        'USER': os.getenv('USER','postgres'),             # Użytkownik bazy danych
        'PASSWORD': os.getenv('PASSWORD', 'admin-password-change-me'),               # Hasło do bazy danych
        'HOST': os.getenv('HOST','localhost'),                     # Adres serwera bazy danych zazwyczaj localhost)
        'PORT': os.getenv('PORT','5432'),                          # Domyślny port PostgreSQL (5432)
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

INTERNAL_IPS = [
    '127.0.0.1',
]

# locmem
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#         'LOCATION': 'unique-snowflake', # Nazwa unikalna dla instancji
#     }
# }

# pojawiły się nowe pliki w folderze django_cache
# FileBased
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'django_cache'), # Ścieżka do katalogu z plikami cache
    }
}

# Konfiguracja Celery
# Adres URL do naszego brokera wiadomości (Redis)
CELERY_BROKER_URL = 'redis://localhost:6379/0'

# Adres URL do backendu wyników (możemy użyć tego samego Redisa)
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# Ustawienie akceptowanego formatu treści
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Ustawienie strefy czasowej
CELERY_TIMEZONE = 'Europe/Warsaw'

# Konfiguracja Celery Beat
CELERY_BEAT_SCHEDULE = {
    # Nazwa zadania (dowolna, ale unikalna)
    'send-summary-every-5-minutes': {
        # Ścieżka do zadania, które ma być wykonane
        'task': 'api.tasks.send_periodic_summary',
        # Harmonogram: uruchom co 5 minut
        'schedule': 300.0, # w sekundach
        # Argumenty przekazywane do zadania
        'args': (['user1@example.com', 'user2@example.com'],), # zawsze tupla
    },
    'cleanup-database-daily': {
        'task': 'api.tasks.cleanup_old_logs',
        # Uruchom codziennie o 20:29 
        'schedule': crontab(hour=20, minute=29),
    },
    # (29) Zadanie 4
    'log-timestamp-every-10-seconds': {
        'task': 'api.tasks.log_timestamp',
        'schedule': 1000.0,  # co 1000 sekund (zmienione z 10 na 1000 aby nie zaśmiecać kolejki)
    },
    # (29) Zadanie 6
    'count-users-daily': {
        'task': 'api.tasks.count_users',
        'schedule': crontab(hour=23, minute=0),
    },
    # (29) Zadanie 12
    'cleanup-log-entries-daily': {
        'task': 'api.tasks.cleanup_old_log_entries',
        'schedule': crontab(hour=16, minute=44),
    },
    # (29) Zadanie 13
    'fetch-example-title-hourly': {
        'task': 'api.tasks.fetch_example_title',
        'schedule': 3600.0,  # co godzinę
    },

}
# (29) Zadanie 14
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# (29) Zadanie 18
CELERY_TASK_DEFAULT_QUEUE = "default"

CELERY_TASK_QUEUES = ( # zaimportowano na górze from kombu import Queue
    Queue("default"), # celery -A lesson_drf worker -l info -Q default
    Queue("priority_queue"), # celery -A lesson_drf worker -l info -Q priority_queue
)

# Opcjonalnie: routing po nazwie taska
CELERY_TASK_ROUTES = {
    "api.tasks.send_welcome_email": {"queue": "priority_queue"},
}

# (29) Zadanie 19 
# Instalacja i eksploracja Flower
# Celery flower - webowa wersja, podgląd tasków:
# Instalacja: pip install flower
# Najpierw workery:
# celery -A lesson_drf worker -l info -E -n worker_default@%h -Q default
# celery -A lesson_drf worker -l info -E -n worker_priority@%h -Q priority_queue
# Potem Flower:
# celery -A lesson_drf flower
# W przeglądarce: http://127.0.0.1:5555
# Nie da się wywołać z poziomu interfejsu, nie ma przycisku Apply. dokumentacja mówi o osobnym terminalu.