# Generated by Django 5.2.8 on 2025-12-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField()),
                ("model", models.CharField()),
                ("year", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField()),
                ("photo", models.ImageField(upload_to="")),
                ("owner_website", models.URLField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
    ]
