"""
Django settings for lesson_27 project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    #  Django REST Framework
    'rest_framework',
    'rest_framework_simplejwt',
    'djoser',
    'drf_spectacular', # (28)
    # (27) Zadanie 2
    'debug_toolbar',
    # inne aplikacje
    'api',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Ustawiamy drf-spectacular jako domyślny generator schematu
    'DEFAULT_SCHEMA_CLASS':'drf_spectacular.openapi.AutoSchema',
}

# Opcjonalna, dodatkowa konfiguracja Simple JWT

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# Opcjonalna, ale zalecana konfiguracja dla drf-spectacular
SPECTACULAR_SETTINGS = {
    'TITLE': 'Moje Wspaniałe API Projektu',
    'DESCRIPTION': 'Dokumentacja dla API, które robi niesamowite rzeczy.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False, # Zazwyczaj nie chcemy udostępniać pliku schematu publicznie
}

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware', 
                    # ^^^ Dodaj jak najwyżej, ale po GZipMiddleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', # Zarządza sesjami, ustawia ciasteczka
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', # Ochrona przed atakami CSRF (recznie serwowane formularze)
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Dodaje obiekt użytkownika do zapytania (sprawdzi, czy User jest zalogowany)
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'lesson_27.middleware.HTTPMethodMiddleware',
]

ROOT_URLCONF = "lesson_27.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lesson_27.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('ENGINE', 'django.db.backends.postgresql'), # Informuje Django, że używamy PostgreSQL
        'NAME': os.getenv('NAME', 'django_rest_db'),              # Nazwa Twojej bazy danych
        'USER': os.getenv('USER','postgres'),             # Użytkownik bazy danych
        'PASSWORD': os.getenv('PASSWORD', 'admin-password-change-me'),               # Hasło do bazy danych
        'HOST': os.getenv('HOST','localhost'),                     # Adres serwera bazy danych zazwyczaj localhost)
        'PORT': os.getenv('PORT','5432'),                          # Domyślny port PostgreSQL (5432)
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

INTERNAL_IPS = [
    '127.0.0.1',
]

# (27) Zadanie 1
# locmem
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#         'LOCATION': 'unique-snowflake', # Nazwa unikalna dla instancji
#     }
# }

# (27) Zadanie 6 - pojawiły się nowe pliki w folderze django_cache
# FileBased
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'django_cache'), # Ścieżka do katalogu z plikami cache
    }
}