# Generated by Django 5.2.8 on 2026-01-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_logentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=255)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
