# Generated by Django 5.2.8 on 2026-01-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_pagetitle"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                ("classification_result", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
