"""Dodanie tabeli tagów i relacji

Revision ID: 0e6097a2ea56
Revises: 2e02e414aa5c
Create Date: 2025-11-24 00:43:41.290367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e6097a2ea56'
down_revision: Union[str, Sequence[str], None] = '2e02e414aa5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tagi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zadanie_tag',
    sa.Column('zadanie_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tagi.id'], ),
    sa.ForeignKeyConstraint(['zadanie_id'], ['zadania.id'], ),
    sa.PrimaryKeyConstraint('zadanie_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zadanie_tag')
    op.drop_table('tagi')
    # ### end Alembic commands ###
