"""Utworzenie tabeli z data utworzenia

Revision ID: 2e02e414aa5c
Revises: 
Create Date: 2025-11-23 20:25:36.813621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e02e414aa5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zadania',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opis', sa.String(), nullable=False),
    sa.Column('zrobione', sa.Boolean(), nullable=False),
    sa.Column('data_utworzenia', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zadania')
    # ### end Alembic commands ###
