# Generated by Django 5.2.8 on 2025-12-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ogloszenia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ogloszenie",
            name="date_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
